[package]
name = "dirmon"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
configparser = "3.1.0"
crossterm = "0.29.0"
fs_extra = "1.3.0"
log = "0.4.28"
notify = "8.1.0"
ratatui = "0.29.0"
